### ISSUE TITLE
where method cannot be run: NoMethodError: undefined method `type' for "character varying(10)":String

### ISSUE THREAD

**Issue by sshojiro** [fiksu/activerecord-redshift-adapter#21]
I prepared this kind of model:

```
class Redshift < ActiveRecord::Base
    establish_connection :redshift
    self.table_name = "postcode"
end
```

and try this on pry console:

```
[6] pry(main)> Redshift.where(oldpost: 514)

NoMethodError: undefined method `type' for "character varying(10)":String
from /Users/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/time_zone_conversion.rb:60:in `create_time_zone_conversion_attribute?'
```

The target table do not have the column 'type'.

I use Rails 4.2 and ruby 2.2.0.
I hope that you reply to me.

thank you in advance.

**Comment by Yoshyn** [comment]
Hi.

'type' is not a column in your target table. See the code of 'create_time_zone_conversion_attribute' here :
http://apidock.com/rails/ActiveRecord/AttributeMethods/TimeZoneConversion/ClassMethods/create_time_zone_conversion_attribute%3F

Concerning your issue, take a look here : https://github.com/aamine/activerecord4-redshift-adapter
